// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtLq0xPqZDQQJdOx0WyetQ65sk5pEosOw',
    appId: '1:542467668948:web:7d3f0918aa45eedadb7441',
    messagingSenderId: '542467668948',
    projectId: 'uangku-fc476',
    authDomain: 'uangku-fc476.firebaseapp.com',
    storageBucket: 'uangku-fc476.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMpjYAG4OaIqMw9LP-xOxOU0KLDdrTv-E',
    appId: '1:542467668948:android:ec55cac217211e67db7441',
    messagingSenderId: '542467668948',
    projectId: 'uangku-fc476',
    storageBucket: 'uangku-fc476.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCN1qSIPvEPPuGFqbURW2fGN2ajzCIBwc',
    appId: '1:542467668948:ios:8a0a21a8fbce7442db7441',
    messagingSenderId: '542467668948',
    projectId: 'uangku-fc476',
    storageBucket: 'uangku-fc476.firebasestorage.app',
    iosBundleId: 'com.example.uangku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCN1qSIPvEPPuGFqbURW2fGN2ajzCIBwc',
    appId: '1:542467668948:ios:8a0a21a8fbce7442db7441',
    messagingSenderId: '542467668948',
    projectId: 'uangku-fc476',
    storageBucket: 'uangku-fc476.firebasestorage.app',
    iosBundleId: 'com.example.uangku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtLq0xPqZDQQJdOx0WyetQ65sk5pEosOw',
    appId: '1:542467668948:web:bdcafd4f5d7b3a5edb7441',
    messagingSenderId: '542467668948',
    projectId: 'uangku-fc476',
    authDomain: 'uangku-fc476.firebaseapp.com',
    storageBucket: 'uangku-fc476.firebasestorage.app',
  );
}
